version: '3'
services:
    db:
      image: mysql:8.0
      cap_add:
        - SYS_NICE
      restart: always
      environment:
        - MYSQL_DATABASE=crud_golang
        - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      ports:
        - '3306:3306'
      volumes:
        - db:/var/lib/mysql

    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumes: 
        - cache:/data

    # app:
    #   build: .
    #   hostname: app
    #   container_name: app_backend
    #   ports:
    #     - "80:8080"
    #   environment:
    #     PORT: 8080
    #     APP_ENV: "development"
    #     REDIS_HOST: "cache:6379"
    #     REDIS_PASSWORD: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
    #     DB_HOST: "db:3306"
    #     DB_USER: "root"
    #     DB_PASSWORD: "mauFJcuf5dhRMQrjj"
    #     DB_NAME: crud_golang
    #   depends_on:
    #     - db
    #     - cache
    #   healthcheck:
    #     test: ['CMD', 'curl', '-f', 'http://localhost:80/api/v1/health']
    #     interval: 1m30s
    #     timeout: 10s
    #     retries: 3
    
volumes:
  cache:
    driver: local

  db:
    driver: local